[tool.poetry]
name = "data-selection-experiment"
version = "0.1.0"
description = ""
authors = ["ranhomri <ran.homri@tensorleap.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
